sbm/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('', views.sbm_startpage, name='sbm_startpage'),
    # personal academic interest submission
    path('pai/', views.pai, name='sbm_pai'),
    path('ls/', views.ls, name='sbm_ls'),
    path('wtc/', views.wtc, name='sbm_wtc'),
    path('pp/', views.pp, name='sbm_pp'),
    path('course_submission/', views.course_submission, name='sbm_course_submission'),
    path('course_submission/search_courses/', views.search_course),
    path('course_description/<int:course_id>', views.course_description, name='sbm_course_description'),
    path('delete_course_enrollment/<int:ce_id>', views.delete_course_enrollment, name='sbm_delete_course_enrollment'),
    path('delete_answers_text/<question_id>/', views.delete_answers_text, name='sbm_delete_answers_text'),
    path('delete_answers_ls/<question_id>/', views.delete_answers_ls, name='sbm_delete_answers_ls'),
    path('pp/search_courses/', views.search_course),
    path('pp/search_institutes/', views.search_institute),
    path('matching_page/', views.matching, name='sbm_matching'),
    path('perform_matching', views.perform_matching, name='perform_matching'),
    path('change_status/<str:status>/', views.change_status, name='change_status'),
    path('create_feedback',views.create_feedback, name='create_feedback'),
    path('pin_match', views.pin_match, name='pin_match'),
    
]

smartuni/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # admin app
    path('__debug__/', include('debug_toolbar.urls')),  # debug toolbar integration
    path('', include('spc.urls')),  # the main application - see seprate urls definition in spc/urls.py
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spc/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from . import views
import notifications.urls

urlpatterns = [
    path('', views.landing, name='landing'),
    path('about/', views.about, name='about'),
    path('data-privacy/', views.data_privacy, name="data-privacy"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('user/', views.jumpstart, name='jumpstart'),
    path('settings/', views.settings, name='settings'),
    path('user/save_notif_settings', views.save_notif_settings, name='save-notif-settings'),
    path('bugs/report', views.reportBugs, name='report'),
    path('bugs/', views.BugListView.as_view(), name="bugs"),
    path('bugs/<int:pk>', views.BugDetailView.as_view(), name="bug"),
    path('bugs/<int:pk>/change-state', views.change_bug_state, name="change-bug-state"),
    path('buddy/<int:pk>', views.UserDetailView.as_view(), name="user-detail"),
    path('spm/', include('spm.urls')),
    path('sbm/', include('sbm.urls')),
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/list/', views.feedback_list, name='feedback_list'),
    path(r'feedback/detailed/?<int:feedback_id>/', views.feedback_detailed, name='feedback_detailed'),
    path('ajax/load-programs/', views.load_programs, name="load-programs"),
    re_path(r'^download/log/(?P<logfile>(info|debug)\.log(\.[0-9]{4}-[0-9]{2}-[0-9]{2})?)$', views.download_log,
            name='download_log'),
    path('search/', views.search_results, name='search_results'),
    path('search/users', views.search_users, name='search_users'),
    path('search/programs', views.search_programs, name='search_programs'),
    path('search/institutions', views.search_institutions, name='search_institutions'),
    path(r'feedback/detailed/?<int:feedback_id>/', views.feedback_detailed, name='feedback_detailed'),
    path('notifications/', views.notification_history, name='notification_history'),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('readnotification/<int:pk>/', views.read_notification, name="read_notification"),
]

spc/forms.py
from urllib import request
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from spc.models import UserInstitutionProgram, Institution, Program, Feedback, STATUS, Page, SmartUser, Settings, \
    UserSettings, Bug, Messenger, Language
from django.contrib.auth.forms import UserChangeForm
import pytz

class RegisterForm(forms.ModelForm):
    """Creates the registration form with custom username, password and email validation."""
    first_name = forms.CharField(max_length=30, required=True, help_text='Alphanumeric characters only.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Alphanumeric characters only.')
    username = forms.CharField(max_length=30, required=True, help_text='Alphanumeric characters only.')
    password = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(max_length=254, help_text='Required. Insert a valid email address.')

    class Meta:
        model = get_user_model()
        fields = ('username', 'password', 'confirm_password', 'email', 'first_name','last_name')

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        email = cleaned_data.get("email")

        # collects error messages pertaining to the username, email and password in a list
        # in order to raise them all at once
        error_messages = []
        if first_name == '' or first_name is None:
            error_messages.append(forms.ValidationError("Please enter a first name.", code='first_name_err'))

        if username == '' or username is None:
            error_messages.append(forms.ValidationError("Please enter a username.", code='username_err'))

        error_messages = self.validate_password(password, confirm_password, error_messages)

        users = get_user_model()
        if not self.validate_email(email) or users.objects.filter(email=email).exists():
            error_messages.append(
                forms.ValidationError("The email is not correct. Please use your uos or uni-osnabrueck address.",
                                      code='email_err'))

        # raise all errors at once if there are any
        if error_messages:
            raise forms.ValidationError(error_messages)

    @staticmethod
    def validate_email(email):
        """Checks if the email address is from the university of Osnabrück (@uos.de or @uni-osnabrueck.de)
        and returns True if the email is valid, False otherwise"""

        try:
            provider = str(email).split('@')[1]
        except (NameError, IndexError, RuntimeError):
            return False
        if provider not in ["uos.de", "uni-osnabrueck.de","uni-osnabrück.de"]:
            return False
        return True

    @staticmethod
    def validate_password(password, confirm_password, error_messages):
        """Checks if the password is at least 8 and at most 30 characters long and matches the confirmation password.
        It returns a list of ValidationError messages"""

        if password == '' or password is None:
            error_messages.append(
                forms.ValidationError("Please enter a password that is at least 8 and at most 30 characters long.",
                                      code='password_err'))
        else:
            password = password.strip()
            confirm_password = confirm_password.strip()
            if len(password) < 8:
                error_messages.append(forms.ValidationError("Password too short. Please enter at least 8 characters."))
            elif password != confirm_password:
                error_messages.append(forms.ValidationError("The passwords did not match!", code='password_err'))
        return error_messages

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data.get("password"))
        if commit:
            user.save()
        return user


class PasswordChangeForm(forms.ModelForm):
    """Creates the form for resetting the password when logged in."""
    user_id = forms.IntegerField()
    password = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput())
    confirm_password = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput())
    old_password = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('user_id', 'password', 'confirm_password', 'old_password')

    def clean(self):
        cleaned_data = super(PasswordChangeForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        old_password = cleaned_data.get("old_password")
        user = get_user_model().objects.get(id=self.cleaned_data.get("user_id"))

        # validate the new password only if the user has validated their identity
        if user.check_password(old_password):
            if user.check_password(password):
                # the new password should be different from the old one
                raise forms.ValidationError("Your new password cannot be the same as your old password.")
            error_message = []
            error_message = RegisterForm.validate_password(password, confirm_password, error_message)
            if error_message:
                # the new password doesn't meet the requirements
                raise forms.ValidationError(error_message)
        else:
            # if a wrong old password is provided, the user cannot change their password
            raise forms.ValidationError("Wrong password. Please enter your correct old password.")

    def save(self, commit=True):
        user = get_user_model().objects.get(id=self.cleaned_data.get("user_id"))
        user.set_password(self.cleaned_data.get("password"))
        if commit:
            user.save()
        return user


class ProfileSettingsForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    email = forms.EmailField()
    dob = forms.DateField(label='Date of birth', widget=forms.DateInput(attrs={"type": "date"}))
    on_site = forms.ChoiceField(widget=forms.RadioSelect(),choices=((True,"On Site"),(False, "Remote")),label="Are you a remote or on site student")
    institution_1 = forms.ModelChoiceField(queryset=Institution.objects.all(), widget=forms.Select(attrs={'placeholder': 'Institution'}), help_text="Select your institution (e.g. University)")
    institution_2 = forms.ModelChoiceField(queryset=Institution.objects.all(),widget=forms.Select(attrs={'placeholder': 'Institution 2 - optional'}), help_text="Select your institution (e.g. University) if you're studying at two insitutions at the same time or you can also select past institutions")
    program_1 = forms.ModelChoiceField(queryset=Program.objects.all(), widget=forms.Select(attrs={'placeholder': 'Program of study'}), help_text="Select your study program")
    program_2 = forms.ModelChoiceField(queryset=Program.objects.all(), widget=forms.Select(attrs={'placeholder': 'Program of study 2 - optional'}), help_text="Select a second study program you are currently enrolled in or have benn enrolled in")
    pic = forms.ImageField(widget=forms.FileInput(attrs={'class': 'input-group-text'}), label="Select profile picture")
    bio = forms.CharField(widget=forms.Textarea, required=False)
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '+XX XXX XXXXXXXXXX', 'type':'tel'}), label="Phone number (please include country code)", required=False)
    messenger = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), queryset=Messenger.objects.all(), label='Which messengers do you use?', required=False)
    language = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(attrs={'class': 'select2'}), queryset=Language.objects.all(),
                                               label='Which languages do you speak?', required=False)
    timezone = forms.ChoiceField(choices=tuple(zip(pytz.all_timezones, pytz.all_timezones)), widget=forms.Select(attrs={'placeholder': 'Timezone'}), help_text="Choose your Timezone:")

    last_name.required =False
    dob.required = False
    institution_1.required = False
    program_1.required = False
    institution_2.required = False
    program_2.required = False
    on_site.required=False
    pic.required = False

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'dob', 'institution_1', 'institution_2', 'program_1', 'program_2',
                  'pic', 'bio', 'phone', 'on_site', 'messenger', 'language', 'timezone')

    def clean(self):
        inst_1 = self.cleaned_data.get("institution_1")
        inst_2 = self.cleaned_data.get("institution_2")
        prog_1 = self.cleaned_data.get("program_1")
        prog_2 = self.cleaned_data.get("program_2")

        # we only need to validate the institution and program fields if the form fields have changed
        changed_fields = self.changed_data
        if 'institution_1' in changed_fields or 'program_1' in changed_fields:
            self.validate_inst_program(inst_1, prog_1)

        if 'institution_2' in changed_fields or 'program_2' in changed_fields:
            self.validate_inst_program(inst_2, prog_2)

    def save(self, commit=True):
        inst_1 = self.cleaned_data.get("institution_1")

spc/templates/spc/_search_institutions.html
<table class="table table-striped table-responsive">
    <thead>
    <tr>
        <th scope="col" class="w-25">Institution Name</th>
        <th scope="col">Programs</th>
    </tr>
    </thead>
    <tbody>
    {% for inst in obj.itertuples %}
    <tr>
        <td>{{ inst.institution_name }}</td>
        <td><div id="initialprograms">{{ inst.programs|truncatewords:25 }}</div>
        <div class="collapse" id="allprograms{{ inst.id }}">{{ inst.programs }}</div>
        <a data-bs-toggle="collapse" href="#allprograms{{ inst.id }}">Show more...</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

spc/templates/spc/_search_users.html
<table class="table table-striped table-responsive">
    <thead>
    <tr>
        <th scope="col">Username</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Academic Interests</th>
    </tr>
    </thead>
    <tbody>
    {% for user in obj.itertuples %}
    <tr>
        <td><a href="{% url "user-detail" user.id|add:"0" %}">{{ user.username }}</a></td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.documents }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

spc/templates/spc/bug_detail_view.html
{% extends 'spc/base.html' %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
    <div class="p-3">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="col-10">Bug #{{ object.id }}</h1>
            {% if object.state == 'o' %}
                <a href="{% url 'change-bug-state' object.id %}" class="btn btn-secondary">Mark as "In progress"</a>
            {% elif object.state == 'i' %}
                <a href="{% url 'change-bug-state' object.id %}" class="btn btn-secondary">Mark as "Closed"</a>
            {% endif %}
        </div>
        <div class="row border-bottom">
            <div class="col-sm-6">
                <p><strong>Module:</strong> {{ object.module_id.page_name }}</p>
                <p><strong>State:</strong>
                    {% if object.state == "o" %}
                        Open
                    {% elif object.state == "i" %}
                        In Progress
                    {% else %}
                        Closed
                    {% endif %}
                </p>
            </div>
            <div class="col-sm-6">
                <p><strong>Submitted by:</strong> {{ object.user_id.username }}</p>
                <p><strong>Submitted at:</strong> {{ object.created_at }}</p>
                {% if object.closed_at %}<p><strong>Closed at:</strong> {{ object.closed_at }}</p>{% endif %}
            </div>
        </div>
        <div class="row mt-3">
            <p class="large-text"><strong>Description: </strong></p>
            <p>{{ object.description }}</p>
        </div>
        <div class="mt-3">
            <p><strong>Related Logfile:</strong></p>
            {% if logname %}
                <p>
                    {{ logname }}
                    <button type="button" class="btn btn-primary" id="download-log"
                            data-download-url="{% url 'download_log' logfile=logname %}"
                            value="{{ logname }}" name="logfile_name">
                        <i data-feather="download"></i>
                    </button>
                </p>
            {% else %}
                No related log files found.
            {% endif %}
            </div>
    </div>
<script src="{% static 'spc/logfile-download.js' %}"></script>
{% endblock %}

spc/templates/spc/feedback.html
<!DOCTYPE html>
{% extends 'spc/base.html' %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'spc/dashboard.css' %}">

{% block content %}
{% bootstrap_messages %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Report Feedback</title>
        <br>
        <h5 class="form-label">We value your feedback, {{ request.user }}!</h5>
    </head>

    <body>
    {{ form.path }}
    <form method="post">
        {% csrf_token %}
        <br><br>
        <div class="form-label">Which page would you like to provide feedback on?</div>
        <select class="form-select" id="module" name="module" style="position: relative; width: 30%; height: 5%;">
            {% for module in modules %}
            <option value="{{ module.id }}" {% if module.url_pattern == origin %} selected {% endif %}> {{ module.page_name }}</option>
            {% endfor %}
        </select>


        <select class="form-select" id="user" name="user" style="display: none">
            <option> {{ request.user.id }}</option>
        </select>


        <br><br>
        <div class="form-label">How satisfied are you with the selected page? (Optional)</div>
        <div>
            <input type="radio" class="form-check-input" id="rate5" name="rating" value="5" />
            <label for="star5" title="text">Extremely!</label>
            <input type="radio" class="form-check-input" id="rate4" name="rating" value="4" />
            <label for="star4" title="text">A Lot</label>
            <input type="radio" class="form-check-input" id="rate3" name="rating" value="3" />
            <label for="star3" title="text">I'm Neutral</label>
            <input type="radio" class="form-check-input" id="rate2" name="rating" value="2" />
            <label for="star2" title="text">Bit of a Let Down</label>
            <input type="radio" class="form-check-input" id="rate1" name="rating" value="1" />
            <label for="star1" title="text">Not at All</label>
        </div>

        <br><br>
        <div class="form-label">Please describe your experience with this service in detail in the space below:</div>
        <textarea id="feedback" name="feedback" class="form-control" style="width:90%; text-align:left" cols="70" rows="10">
        </textarea>

        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>
    </body>




    </html>
{% endblock %}

spc/templates/spc/settings.html
<!-- templates/customized_crispy_signup.html -->
{% extends 'spc/base.html' %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    {# display messages #}
    {% bootstrap_messages %}
    <form method="post" novalidate enctype="multipart/form-data" id="general-settings-form" data-program-url="{% url 'load-programs' %}">
        {% csrf_token %}
        <div style="display: block; margin-left: 5%; margin-right: 5%; margin-top: 5%; border-radius: 15px; padding: 24px; background-color: #ffffff">
            <img src="{{ request.user.pic.url }}" alt="Avatar" width="200px" height="200px" style="display: block; margin-left: auto; margin-right: auto; margin-bottom: 24px; border-radius: 50%">
            <div class=”input-group” style="margin-right: 17%; margin-left: 17%; display: block";>
                <div class="input-group custom-file-button">
                    <label for="id_pic" class="input-group-text">Select profile picture</label>
                    <input type="file" name="pic" class="form-control" accept="image/*" id="id_pic">
                </div>
            </div>
        </div>

        <div class="accordion settings">
            <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                        Profile Information
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne">
                    <div class="accordion-body">
                        <div class="row">
                           <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin-left: auto;">
                                    {{ form.first_name|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                    {{ form.last_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin-left: auto;">
                                    {{ form.email|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6"style="display: block; margin-right: auto;">
                                    {{ form.dob|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin-left: auto;">
                                    {{ form.institution_1|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                    {{ form.program_1|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin-left: auto;">
                                    {{ form.institution_2|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                    {{ form.program_2|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin-left: auto;">
                                    {{ form.on_site|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin-left: auto;">
                                    {{ form.phone|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin: auto;">
                                    {{ form.messenger|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-12" style="display: block; margin: auto;">
                                    {{ form.bio|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin: auto;">
                                    {{ form.language|as_crispy_field }}
                                </div>
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6" style="display: block; margin-right: auto;">
                                    {{ form.timezone|as_crispy_field }}
                                </div>
                            </div>

                            </div>
                        </div>
                    </div>
            </div>
    </form>
            <div class="accordion-item">
            <form method="post" novalidate id="notif-settings-form">
            {% csrf_token %}
                <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                        Notification Settings
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                    <div class="accordion-body">
                        {% for category, setting in settings.items %}
                            <h6>
                                {% if category == 'SPC' %}General{% endif %}
                                {% if category == 'SPM' %}Study Planner{% endif %}
                                {% if category == 'SBM' %}Study Buddy Match{% endif %}
                            </h6>
                            <div class="table-responsive">
                            <table class="table table-striped table-hover">
                            <tbody>
                            {% for name, description in setting.items %}
                                {% for key, value in notif_initial.items %}
                                    {% if key == name %}
                                    <tr><td class="align-middle">{{ description }}</td>
                                    <td><div class="btn-group" role="group">
                                      <input type="radio" name="{{ name }}" class="btn-check notif-setting-button"
                                             value="0" id="radioBtn{{ forloop.counter }}-1" {% if key == name and value == '0' %}checked{% endif %}>
                                      <label class="btn btn-primary" for="radioBtn{{ forloop.counter }}-1">None</label>

                                      <input type="radio" name="{{ name }}" class="btn-check notif-setting-button"
                                             value="1" id="radioBtn{{ forloop.counter }}-2" {% if key == name and value == '1' %}checked{% endif %}>
                                      <label class="btn btn-primary" for="radioBtn{{ forloop.counter }}-2">In-App</label>

                                      <input type="radio" name="{{ name }}" class="btn-check notif-setting-button"
                                             value="2" id="radioBtn{{ forloop.counter }}-3" {% if key == name and value == '2' %}checked{% endif %}>
                                      <label class="btn btn-primary" for="radioBtn{{ forloop.counter }}-3">E-Mail</label>

                                      <input type="radio" name="{{ name }}" class="btn-check notif-setting-button"
                                             value="3" id="radioBtn{{ forloop.counter }}-4" {% if key == name and value == '3' %}checked{% endif %}>
                                      <label class="btn btn-primary" for="radioBtn{{ forloop.counter }}-4">Both</label>
                                    </div></td>
                                    </tr>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                            </tbody>
                            </table>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </form>
            </div>
        </div>
        <div style="display: block; margin: 1% 5%; border-radius: 15px; padding: 24px; background-color: #ffffff">
            <div class="row">
                <button type="submit" id="save-settings" class="form-group col-4 btn btn-primary mt-4"
                        style="display: block; margin-left: auto; margin-right: 24px;">Save All</button>
                <a href="{% url 'password_change' %}" class="form-group col-4 btn btn-primary mt-4"
                   style="display: block; margin-right: auto;">Change Password</a>
            </div>
        </div>

        <script>
            $(document).ready(() => {
                $('.select2').select2().wrap('<div></div>');
                $('.select2-container').width("100%");
                $('#save-settings').click(function(event) {
                    $.ajax({
                        method: "POST",
                        url: "/user/save_notif_settings",
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest',
                            'X-CSRFToken': $("#notif-settings-form > input[name=csrfmiddlewaretoken]").val()
                        },
                        data: $('#notif-settings-form').serialize(),
                        success: function(data) {
                            $('#general-settings-form').submit()
                        }
                    })
                });
            })
    </script>
    <script src="{% static 'spc/filter-programs.js' %}" ></script>

{% endblock %}