sbm/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('', views.sbm_startpage, name='sbm_startpage'),
    # personal academic interest submission
    path('pai/', views.pai, name='sbm_pai'),
    path('ls/', views.ls, name='sbm_ls'),
    path('wtc/', views.wtc, name='sbm_wtc'),
    path('pp/', views.pp, name='sbm_pp'),
    path('course_submission/', views.course_submission, name='sbm_course_submission'),
    path('course_submission/search_courses/', views.search_course),
    path('course_description/<int:course_id>', views.course_description, name='sbm_course_description'),
    path('delete_course_enrollment/<int:ce_id>', views.delete_course_enrollment, name='sbm_delete_course_enrollment'),
    path('delete_answers_text/<question_id>/', views.delete_answers_text, name='sbm_delete_answers_text'),
    path('delete_answers_ls/<question_id>/', views.delete_answers_ls, name='sbm_delete_answers_ls'),
    path('pp/search_courses/', views.search_course),
    path('pp/search_institutes/', views.search_institute),
    path('matching_page/', views.matching, name='sbm_matching'),
    path('perform_matching', views.perform_matching, name='perform_matching'),
    path('change_status/<str:status>/', views.change_status, name='change_status'),
    path('create_feedback',views.create_feedback, name='create_feedback'),
    path('pin_match', views.pin_match, name='pin_match'),
    
]

smartuni/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),  # admin app
    path('__debug__/', include('debug_toolbar.urls')),  # debug toolbar integration
    path('', include('spc.urls')),  # the main application - see seprate urls definition in spc/urls.py
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('weekly/<str:date>/', views.WeeklyListView.as_view(), name='weekly'),
    path('daily/<str:date>/', views.DailyListView.as_view(), name='daily'),
    path('', views.planner_startpage, name='planner-startpage'),
    path('weekly/', views.weekly_to_date, name='weekly-to-date'),
    path('daily/', views.daily_to_date, name='daily-to-date'),

    path('<str:overview>/<str:date>/insertSmartTasks/', views.insertSmartTasksIntoCalendar,
         name='calendar-insert-smart-tasks'),
]

# <type:name> can be used as url parameters
urlpatterns += [
    path('<str:overview>/<str:date>/event/new/', views.EventCreate.as_view(), name='event-new'),
    path('<str:overview>/<str:date>/task/new/', views.TaskCreate.as_view(), name='task-new'),
    path('<str:overview>/<str:date>/<uuid:pk1>/<str:pk2>/updateDecisionTreeData/', views.createDecisionTreeEntry,
         name='decision-tree-task-new')
]

urlpatterns += [
    path('<str:overview>/<str:date>/event/<uuid:pk>/update/', views.EventUpdate.as_view(), name='event-update'),
    path('<str:overview>/<str:date>/task/<uuid:pk>/update/', views.TaskUpdate.as_view(), name='task-update'),
]

urlpatterns += [
    path('<str:overview>/<str:date>/event/<uuid:pk>/delete/', views.EventDelete.as_view(), name='event-delete'),
    path('<str:overview>/<str:date>/task/<uuid:pk>/delete/', views.TaskDelete.as_view(), name='task-delete'),
]

urlpatterns += [
    path('<str:overview>/<str:date>/event/<uuid:pk>/', views.EventDetailView.as_view(), name='event-detail'),
    path('<str:overview>/<str:date>/task/<uuid:pk>/', views.TaskDetailView.as_view(), name='task-detail'),
]

urlpatterns += [
    path('<str:overview>/<str:date>/updateTaskCalendar/', views.updateTaskForCalendar, name='calendar-update'),
    path('<str:overview>/<str:date>/task/<uuid:pk>/update/updateTaskLength/',
         views.updateTaskLengthAfterDurationChange, name='task-update-length'),
    path('<str:overview>/<str:date>/removeTaskCalendar/', views.removeTaskFromCalendar, name='calendar-update-removal'),
    path('<str:overview>/<str:date>/task/<uuid:pk>/toggleComplete/', views.completeTask, name='complete'),
]

urlpatterns += [
    path('<str:overview>/<str:date>/smartPlanningSettings/', views.SmartPlanning.as_view(),
         name='smart-planning-settings'),
    path('<str:overview>/<str:date>/insertSmartTasks/openTasksLeft/', views.OpenTasks.as_view(),
         name='open-task-warning'),
]

spm/models.py
import datetime
import uuid
from django.db import models
from django.conf import settings
from django.urls import reverse
from .fields import CustomDurationModelField


# own model because new choice options should be added
# new options can be added in the /admin/ url
class Category(models.Model):
    name = models.CharField('category', max_length=16,
                            help_text='Enter a category (e.g. "work")', null=True, blank=True)
    color = models.CharField(max_length=7, default='#334B7B')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        if self.name is None:
            user = str(self.user)
            return 'default ' + user + ' category'
        return self.name


class Task(models.Model):

    # add choice options hard coded only if no new options should be added
    class Priority(models.IntegerChoices):
        HIGH = (3, 'high')
        MEDIUM = (2, 'medium')
        LOW = (1, 'low')

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True)
    title = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    deadline_date = models.DateField()
    deadline_time = models.TimeField()
    duration = CustomDurationModelField()
    # integer choice field makes interpolation later on possible
    priority = models.IntegerField(choices=Priority.choices, default=Priority.LOW)
    description = models.TextField(max_length=2000, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    startdate = models.DateField(null=True, default=None)  # tasks don't need a date but should be able to get one
    enddate = models.DateField(null=True, default=None)
    starttime = models.TimeField(null=True, default=None)
    endtime = models.TimeField(null=True, default=None)
    # bool to enable easy check of completion
    complete = models.BooleanField(default=False)
    complete_time = models.DateTimeField(null=True, default=None)
    ai_scheduler = models.BooleanField(default=True)

    def get_absolute_url_weekly(self):
        if self.startdate:
            return reverse('task-detail', kwargs={'overview': 'weekly', 'pk': self.id, 'date': self.startdate})
        else:
            return reverse('task-detail', kwargs={'overview': 'weekly', 'pk': self.id, 'date': self.deadline_date})

    def get_absolute_url_daily(self):
        if self.startdate:
            return reverse('task-detail', kwargs={'overview': 'daily', 'pk': self.id, 'date': self.startdate})
        else:
            return reverse('task-detail', kwargs={'overview': 'daily', 'pk': self.id, 'date': self.deadline_date})

    def __str__(self):
        return f'{self.title} until {self.deadline_date}, {self.deadline_time}'


class DecisionTreeTask(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    weekday = models.IntegerField()
    time = models.IntegerField()
    priority = models.IntegerField()
    deadline = models.IntegerField()
    duration = models.IntegerField()
    category = models.IntegerField()
    as_planned = models.BooleanField()


class Weekdays(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    monday = models.BooleanField(default=False)
    tuesday = models.BooleanField(default=False)
    wednesday = models.BooleanField(default=False)
    thursday = models.BooleanField(default=False)
    friday = models.BooleanField(default=False)
    saturday = models.BooleanField(default=False)
    sunday = models.BooleanField(default=False)
    smart_settings = models.BooleanField(default=False)


class Recurrence(models.Model):

    # add choice options hard coded only if no new options should be added
    class RepeatType(models.IntegerChoices):
        WEEK = (1, 'week(s)')
        MONTH = (2, 'month(s)')
        YEAR = (3, 'year(s)')

    groupID = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True)
    weekdays = models.ForeignKey(Weekdays, on_delete=models.CASCADE, null=True, blank=True)
    repeat_freq = models.IntegerField(default=1)
    repeat_type = models.IntegerField(choices=RepeatType.choices, default=RepeatType.WEEK)
    repeat_end = models.DateField()


class Event(models.Model):
    # uuids are standardized values and easier to handle as id than simply counting up
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True)
    title = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    startdate = models.DateField()
    enddate = models.DateField()
    starttime = models.TimeField()
    endtime = models.TimeField()
    location = models.CharField(max_length=100, blank=True)
    comment = models.TextField(max_length=2000, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    recurrence_true = models.BooleanField(default=False)
    recurrence = models.ForeignKey(Recurrence, on_delete=models.CASCADE, null=True, blank=True)
    groupID = models.UUIDField(null=True, blank=True)

    # we need two absolute urls one for each overview
    # because for a method in the html file the parameters can't be called
    def get_absolute_url_weekly(self):
        return reverse('event-detail', kwargs={'overview': 'weekly', 'pk': self.id, 'date': self.startdate})

    def get_absolute_url_daily(self):
        return reverse('event-detail', kwargs={'overview': 'daily', 'pk': self.id, 'date': self.startdate})

    # this will be returned if the object is called as a string e.g. in print methods
    def __str__(self):
        return f'{self.title}: {self.startdate}, {self.starttime} to {self.enddate}, {self.endtime}'


class SmartPlanningSettings(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    weekdays = models.ForeignKey(Weekdays, on_delete=models.CASCADE, null=True, blank=True)
    smart_startdate = models.DateField(null=True)
    smart_enddate = models.DateField()
    smart_starttime = models.TimeField()
    smart_endtime = models.TimeField()


class TemporarySmartTasks(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    task_id = models.CharField(max_length=40)

spm/templates/spm/daily.html
{% extends 'spm/planner_startpage.html' %}

{% load static %}
{% load icon %}

{% block overview %}
<!-- insert daily overview template here -->
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet">


    <div id="calendar-overview" class="fc-daily-calendar">
        <div class="fc-header-toolbar fc-toolbar fc-toolbar-ltr"></div>
        <div aria-labelledby="fc-dom-1" class="fc-view-harness fc-view-harness-active daily_appointments-container"
             style="width: 60%;"></div>
        <div class="slider" id="id_slider"></div>
        <div class="events-daily-wrapper" id="id_events-daily-wrapper" style="width: calc(40% - 10px);">
            <div id="id_events-daily" class="events-daily daily-appointments-container"></div>
        </div>
    </div>

    <script>
        let THRESH = 200;
        function background2TextColor(hex) {
            var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
            var r = parseInt(result[1], 16);
            var g = parseInt(result[2], 16);
            var b = parseInt(result[3], 16);

            if (Math.round(0.21 * r + 0.72 * g + 0.07 * b) > THRESH) {
                return '#000000';
            } else {
                return '#ffffff';
            }
        }

        /* to access the context data in javascript file */
        let date2Initialize = '{{ date }}'

        /* Create a list of all events that should be displayed */
        let eventlist = [];
        let tasklist = [];

        {% if event_list %}
            {% for i in event_list %}
                var backgroundColor = "{{ i.category.color }}";
                var textCol = '#ffffff';
                if (backgroundColor) {
                    textCol = background2TextColor(backgroundColor);
                }

                eventlist.push({
                    id: "{{ i.id }}",
                    title: "{{ i.title }}",
                    start: '{{ i.startdate|date:"Y-m-d" }}' + 'T' + '{{ i.starttime|time:"H:i:i" }}',
                    end: '{{ i.enddate|date:"Y-m-d" }}' + 'T' + '{{ i.endtime|time:"H:i:i" }}',
                    editable: false,
                    backgroundColor: "{{ i.category.color }}",
                    borderColor: "{{ i.category.color }}",
                    textColor: textCol,
                    extendedProps: {
                        edit_href: "{{ i.get_absolute_url_daily }}",
                        location: "{{ i.location }}",
                        comment: "{{ i.comment }}",
                        category: "{{ i.category.name }}",
                        categoryColor: "{{ i.category.color }}",
                        type: "event",
                    }
                })
            {% endfor %}
        {% endif %}

        {% if task_list %}
            {% for i in task_list %}
                {%  if i.startdate %}
                    tasklist.push({
                        title: "{{ i.title }}",
                        start: '{{ i.startdate|date:"Y-m-d" }}' + 'T' + '{{ i.starttime|time:"H:i:i"}}',
                        end: '{{ i.enddate|date:"Y-m-d" }}' + 'T' + '{{ i.endtime|time:"H:i:i"}}',
                        backgroundColor: "#ffffff",
                        borderColor: "{{ i.category.color }}",
                        textColor: "#000000",
                        editable: true,
                        durationEditable: false,
                        id: "{{ i.id }}",
                        display: "auto",
                        extendedProps: {
                            edit_href: "{{ i.get_absolute_url_daily }}",
                            location: "",
                            priority: "{{ i.priority }}",
                            deadline: "{{ i.deadline_date|date:"d.m.Y" }}  {{ i.deadline_time|time:"H:i" }}",
                            description: "{{ i.description }}",
                            categoryColor: "{{ i.category.color }}",
                            type: "task",
                            category: "{{ i.category.name }}",
                            complete: "{{ i.complete }}"
                        }
                    })
                {% endif %}
            {% endfor %}
        {% endif %}

        let categories = [];

        {% if category_list %}
            {% for c in category_list %}
                {# exclude the default category in the list #}
                if ("{{ c.name }}" !== 'None') {
                    categories.push({
                        name: "{{ c.name }}",
                        color: "{{ c.color }}",
                        textColor: background2TextColor("{{ c.color }}"),
                    })
                }
            {% endfor %}
        {% endif %}
    </script>

    {% csrf_token %}
    <script>
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    </script>

    <script src="{% static 'spm/update_database.js' %}"></script>

{% endblock %}

spm/templates/spm/event_form.html
{% if overview == 'weekly' %}
    {% include 'spm/weekly.html' %}
{% elif overview == 'daily' %}
    {% include 'spm/daily.html' %}
{% endif %}

{% load icon %}
{% load static %}

<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet">

<div class="popup">
    <form autocomplete="off" action="" method="post">
        {% csrf_token %}
        {# sturturing into rows using div #}
        {# divs are easier to style and to put into position #}
        <div class="inline-to-block spacing">
            {# sturturing into input elements using div #}
            {# 'input' is the general class that can be reused for every input field followed by field specific styling #}
            {# prevents code duplicates #}
            <div class="input centered-spaced-alignment input-title input-height" id="id_new-event-title">
                {{ form.title }}
                <i class="smart-info tooltip-initiator">
                    {% icon 'info' class="smart-info-icon-secondary" %}
                    <span class="tooltiptext required">
                         This is a required field.
                    </span>
                 </i>
            </div>
            <div class="input centered-spaced-alignment input-category input-height autocomplete">
                {{ cat_form.name }}
                {{ cat_form.color }}
            </div>
            <div class="input centered-spaced-alignment input-close-button input-height">
                {# in forms the default type for buttons is 'submit' so this needs to be set explicitely #}
                <button id="id_close-button-new-event" type="button" class="button close-button">
                    <i class="popup-icons">{% icon 'x' %}</i>
                </button>
            </div>
        </div>
        <div class="inline-to-block spacing">
            {# the spacing between the elements can not be seen because the input class has the white background #}
            {# otherwise we would have to put all the elements in one single line which makes the code very hard to read #}
            <div class="input centered-spaced-alignment event-input-elements input-height">
                {# onlick() is not needed since all of the functinality is in the EventListeners #}
                <button type="button" class="button toggle-button" id="id_startdate-prev">
                    {% icon "chevron-left" %}
                </button>
                {{ form.startdate }}
                <button type="button" class="button toggle-button" id="id_startdate-next">
                    {% icon "chevron-right" %}
                </button>
            </div>
            <div class="input centered-spaced-alignment event-input-elements input-height">
                <button type="button" class="button toggle-button" id="id_enddate-prev" disabled>
                    {% icon "chevron-left" %}
                </button>
                {{ form.enddate }}
                <button type="button" class="button toggle-button" id="id_enddate-next" disabled>
                    {% icon "chevron-right" %}
                </button>
            </div>
            <div class="input centered-spaced-alignment event-input-elements input-height">
                {{ form.location }}
                <i class="popup-icons popup-location-icon" id="id_location-icon">{% icon "map-pin" %}</i>
            </div>
        </div>
        <div class="inline-to-block spacing grid-container">

            <div class="input centered-spaced-alignment event-input-elements input-height grid-element">
                <button type="button" class="button toggle-button" id="id_starttime-prev">
                    {% icon "chevron-left" %}
                </button>
                {{ form.starttime }}
                <button type="button" class="button toggle-button" id="id_starttime-next">
                    {% icon "chevron-right" %}
                </button>
            </div>

            <div class="input centered-spaced-alignment event-input-elements input-height grid-element">
                <button type="button" class="button toggle-button" id="id_endtime-prev">
                    {% icon "chevron-left" %}
                </button>
                {{ form.endtime }}
                <button type="button" class="button toggle-button" id="id_endtime-next">
                    {% icon "chevron-right" %}
                </button>
            </div>

            <div class="input event-input-elements input-height form-comment grid-element">
                {{ form.comment }}
            </div>
            <div class="recurrence-wrapper double-padding">
                <div class="centered-spaced-alignment">
                    <div class="centered-spaced-alignment">
                        {{ form.recurrence_true }}
                        <div id="id_recurring-checkbox-label" class="input-labels"></div>
                    </div>
                    <i class="smart-info tooltip-initiator">
                        {% icon 'info' class="smart-info-icon" %}
                        <span class="tooltiptext">
                            Events can be repeated weekly, monthly or yearly. For a weekly repetition
                            the weekdays on which the event should be repeated can be selected. The weekday
                            of the startdate is mandatory. The update of a repetition pattern is only possible
                            for this and the following events, while title, category, start- and endtime,
                            location and comment get updated for all events of one series.
                        </span>
                    </i>
                </div>
                <div id="id_recurrence-pattern" class="recurrence">
                    <div class="centered-spaced-alignment spacing-top">
                        <div class="input-labels">
                            Repeat every
                        </div>
                        <div class="recurrence-input-column-width centered-spaced-alignment">
                            <div class="input centered-spaced-alignment input-recurrence input-recurrence-freq">
                                {{ recurrence_form.repeat_freq }}
                            </div>
                            <div class="input centered-spaced-alignment input-recurrence input-recurrence-type">
                                {{ recurrence_form.repeat_type }}
                            </div>
                            <div class="input-labels">
                                until
                            </div>
                            <div class="input centered-spaced-alignment input-recurrence input-recurrence-end">
                                <button type="button" class="button toggle-button" id="id_repeat-end-prev">
                                    {% icon "chevron-left" %}
                                </button>
                                {{ recurrence_form.repeat_end }}
                                <button type="button" class="button toggle-button" id="id_repeat-end-next">
                                    {% icon "chevron-right" %}
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="centered-spaced-alignment double-spacing-top">
                        <div class="input-labels">
                            Recurring on
                        </div>
                        <div class="input-recurring-weekdays recurrence-input-column-width">
                            {{ weekdays_form.monday }}
                            <label data-weekday-label for="id_monday">Mon</label>
                            {{ weekdays_form.tuesday }}
                            <label data-weekday-label for="id_tuesday">Tue</label>
                            {{ weekdays_form.wednesday }}
                            <label data-weekday-label for="id_wednesday">Wed</label>
                            {{ weekdays_form.thursday }}
                            <label data-weekday-label for="id_thursday">Thu</label>
                            {{ weekdays_form.friday }}
                            <label data-weekday-label for="id_friday">Fri</label>
                            {{ weekdays_form.saturday }}
                            <label data-weekday-label for="id_saturday">Sat</label>
                            {{ weekdays_form.sunday }}
                            <label data-weekday-label for="id_sunday">Sun</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="submit-button" id="id_submit-button-new-event" disabled>
            {% icon "check" class="submit-icon" %}
        </button>
    </form>
</div>
<div id="id_warning-popup-new-event" class="warning-popup">
    <p class="first-par-warning-popup"> Do you want to leave? </p>
    <p class="second-par-warning-popup"> Changes will be discarded.</p>
    <row>
        {# redirect to overview url #}
        {# if a goes before the button the text does not appear as a link #}
        <a href="{% url overview date %}">
            <button type="button" class="warning-popup-buttons gray-button-warning-popup">
                DISCARD
            </button>
        </a>
        <button id="id_cancel-button-warning-popup" type="button"
                class="warning-popup-buttons orange-button-warning-popup">
            CANCEL
        </button>
    </row>
</div>
<div class="overlay" id="id_overlay-new-event"></div>

{# at the bottom where the file is loaded to solve firefox issues #}
<script src="{% static 'spm/event_form_formatting.js' %}"></script>
<script src="{% static 'spm/category_form_autocomplete.js' %}"></script>
<script>
    autocomplete(document.getElementById("id_name"), document.getElementById("id_color"), categories)
</script>

spm/templates/spm/task_confirm_delete.html
{% if overview == 'weekly' %}
    {% include 'spm/weekly.html' %}
{% elif overview == 'daily' %}
    {% include 'spm/daily.html' %}
{% endif %}

<div class="warning-popup active">
    <div class="delete-svg"></div>
    <p class="first-par-warning-popup">
        This task will be deleted.
    </p>
    <p class="second-par-warning-popup">
        Deleted tasks cannot be recovered.
    </p>
    <button class="warning-popup-buttons gray-button-warning-popup" onclick="history.back()">
        CANCEL
    </button>
    <form action="" method="POST">
        {% csrf_token %}
        <button class="warning-popup-buttons red-button-warning-popup" type="submit">
            DELETE
        </button>
    </form>
</div>
<div class="overlay"></div>

spm/templates/spm/weekly.html
{% extends 'spm/planner_startpage.html' %}

{% load static %}
{% load icon %}

{% block overview %}
<!-- insert weekly overview template here -->
    <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" rel="stylesheet">

    <div id="calendar-overview"></div>

    <script>
        let THRESH = 200;
        function background2TextColor(hex) {
            var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
            var r = parseInt(result[1], 16);
            var g = parseInt(result[2], 16);
            var b = parseInt(result[3], 16);

            if (Math.round(0.21 * r + 0.72 * g + 0.07 * b) > THRESH) {
                return '#000000';
            } else {
                return '#ffffff';
            }
        }
        /* to access the context data in javascript file */
        let date2Initialize = '{{ date }}'

        /* Create a list of all events that should be displayed */
        let eventlist = [];
        let tasklist = [];

        {% if event_list %}
            {% for i in event_list %}
                var backgroundColor = "{{ i.category.color }}";
                var textCol = '#ffffff';
                if (backgroundColor) {
                    textCol = background2TextColor(backgroundColor);
                }

                eventlist.push({
                    id: "{{ i.id }}",
                    title: "{{ i.title }}",
                    start: '{{ i.startdate|date:"Y-m-d" }}' + 'T' + '{{ i.starttime|time:"H:i:i"}}',
                    end: '{{ i.enddate|date:"Y-m-d" }}' + 'T' + '{{ i.endtime|time:"H:i:i"}}',
                    editable: false,
                    backgroundColor: "{{ i.category.color }}",
                    borderColor: "{{ i.category.color }}",
                    textColor: textCol,
                    extendedProps: {
                        edit_href: "{{ i.get_absolute_url_weekly }}",
                        location: "{{ i.location }}",
                        category: "{{ i.category.name }}",
                        type: "event",
                    }
                })
            {% endfor %}
        {% endif %}

        {% if task_list %}
            {% for i in task_list %}
                {%  if i.startdate %}
                    tasklist.push({
                        title: "{{ i.title }}",
                        start: '{{ i.startdate|date:"Y-m-d" }}' + 'T' + '{{ i.starttime|time:"H:i:i"}}',
                        end: '{{ i.enddate|date:"Y-m-d" }}' + 'T' + '{{ i.endtime|time:"H:i:i"}}',
                        backgroundColor: "#ffffff",
                        borderColor: "{{ i.category.color }}",
                        textColor: "#000000",
                        editable: true,
                        display: "auto",
                        durationEditable: false,
                        id: "{{ i.id }}",
                        extendedProps: {
                            edit_href: "{{ i.get_absolute_url_weekly }}",
                            location: "",
                            id: "{{ i.id }}",
                            type: "task",
                            category: "{{ i.category.name }}",
                            complete: "{{ i.complete }}",
                        }
                    })
                {% endif %}
            {% endfor %}
        {% endif %}

        let categories = [];

        {% if category_list %}
            {% for c in category_list %}
                {# exclude the default category in the list #}
                if ("{{ c.name }}" !== 'None') {
                    categories.push({
                        name: "{{ c.name }}",
                        color: "{{ c.color }}",
                        textColor: background2TextColor("{{ c.color }}"),
                    })
                }
            {% endfor %}
        {% endif %}
    </script>

    {% csrf_token %}
    <script>
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    </script>

    <script src="{% static 'spm/update_database.js' %}"></script>

{% endblock %}